name:                exercise1
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/tr00per/HaskellUniversity-solutions/exercise1#readme
license:             BSD3
author:              Artur Czajka
maintainer:          arturczajka@gmail.com
copyright:           2017 Artur Czajka
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  ex1:
    source-dirs:      src1
    main:             Main.hs
  ex2:
    source-dirs:      src2
    main:             Main.hs
  ex3:
    source-dirs:      src3
    main:             Main.hs
